# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Xin Chao
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
project_short_description: A JupyterLab extension.
python_name: jupyterlab_apod
repository: https://github.com/EURICIA/JupyterLab-Extension
test: true

